# Generated by Django 4.0.6 on 2023-01-13 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя преподавателя')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('vk', models.URLField(verbose_name='ВК')),
                ('youtube', models.URLField(verbose_name='Ютуб')),
                ('telegram', models.URLField(verbose_name='Телеграм')),
                ('video', models.URLField(verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество занятий')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Style_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='danceschool.teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('phone', models.CharField(blank=True, default='89', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default='@tpu.ru', max_length=254, null=True)),
                ('visits', models.TextField(blank=True, default='', null=True, verbose_name='Посещения')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='danceschool.ticket', verbose_name='Абонемент')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
